/**
 * Comprehensive Indian Agricultural Produce Catalogue
 * 57 distinct commercial crop varieties across 7 categories
 * All lots formatted with authentic APMC mandi pricing, MSP benchmarks,
 * AI quality scores, moisture ratings, and real farming locations.
 */

// Helper to generate dynamic future auction end dates
const getAuctionEnd = (hoursAhead) => {
  const d = new Date();
  d.setHours(d.getHours() + hoursAhead);
  return d.toISOString();
};

export const mockCrops = [
  // ==========================================
  // 1. CEREALS (8 Crops)
  // ==========================================
  {
    id: "1",
    name: "Basmati Rice",
    category: "Cereals",
    variety: "Pusa 1121",
    quantity: 50,
    unit: "quintal",
    quality: "A",
    moisture: 12.5,
    aiQualityScore: 94,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.8,
    demandLevel: "High",
    predictedPrice: 4350,
    priceLogic: {
      baseMSP: 3800,
      gradeMultiplier: 1.12,
      moistureAdjustment: "+₹150 (Optimal <13%)",
      demandBoost: "+₹250 (Export surge)",
    },
    bestPlaceToSell: {
      mandi: "Karnal Grain Market",
      distanceKm: 12,
      mandiPrice: 4380,
      estimatedFreight: 180,
      netProfitPerQuintal: 4200,
    },
    whenToSell: {
      recommendation: "Hold 2 Weeks",
      projectedIncrease: "+12%",
      reasoning: "Festival demand spike expected around harvest completion.",
    },
    floorPrice: 3500,
    currentBid: 4200,
    totalBids: 12,
    harvestDate: "2025-01-10",
    location: "Karnal",
    state: "Haryana",
    farmerName: "Rajesh Kumar",
    farmerId: "F001",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(36),
    logisticsMode: "app_arranged",
    weightConfirmed: 50,
    pickupSchedule: { date: "2025-01-06", time: "10:00 AM" },
  },
  {
    id: "2",
    name: "Wheat",
    category: "Cereals",
    variety: "HD 3086 (Pusa Gautami)",
    quantity: 100,
    unit: "quintal",
    quality: "A",
    moisture: 11.8,
    aiQualityScore: 92,
    aiSuggestedGrade: "A",
    farmerRating: 4.7,
    buyerRating: 4.9,
    demandLevel: "High",
    predictedPrice: 2700,
    priceLogic: {
      baseMSP: 2275,
      gradeMultiplier: 1.08,
      moistureAdjustment: "+₹120 (Dry & clean)",
      demandBoost: "+₹180 (Flour mill demand)",
    },
    bestPlaceToSell: {
      mandi: "Ludhiana Central Mandi",
      distanceKm: 8,
      mandiPrice: 2720,
      estimatedFreight: 120,
      netProfitPerQuintal: 2600,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+2%",
      reasoning: "Current prices are peak; major supply arrivals next week.",
    },
    floorPrice: 2200,
    currentBid: 2650,
    totalBids: 8,
    harvestDate: "2025-01-05",
    location: "Ludhiana",
    state: "Punjab",
    farmerName: "Gurpreet Singh",
    farmerId: "F002",
    imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(48),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 100,
    pickupSchedule: { date: "2025-01-05", time: "02:00 PM" },
  },
  {
    id: "7",
    name: "Sharbati Wheat",
    category: "Cereals",
    variety: "C-306 Golden Grain",
    quantity: 75,
    unit: "quintal",
    quality: "A",
    moisture: 10.5,
    aiQualityScore: 96,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 5.0,
    demandLevel: "Surge",
    predictedPrice: 3850,
    priceLogic: {
      baseMSP: 2425,
      gradeMultiplier: 1.25,
      moistureAdjustment: "+₹180 (Sub-11% Premium)",
      demandBoost: "+₹450 (Chakki Atta Premium)",
    },
    bestPlaceToSell: {
      mandi: "Sehore Krishi Mandi",
      distanceKm: 14,
      mandiPrice: 3900,
      estimatedFreight: 150,
      netProfitPerQuintal: 3750,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+4%",
      reasoning: "High direct retail miller demand for MP Sharbati.",
    },
    floorPrice: 3200,
    currentBid: 3750,
    totalBids: 14,
    harvestDate: "2025-01-08",
    location: "Sehore",
    state: "Madhya Pradesh",
    farmerName: "Shivraj Malviya",
    farmerId: "F007",
    imageUrl: "https://images.unsplash.com/photo-1508615039623-a25605d2b022?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(28),
    logisticsMode: "app_arranged",
    weightConfirmed: 75,
    pickupSchedule: { date: "2025-01-09", time: "11:00 AM" },
  },
  {
    id: "8",
    name: "Sona Masoori Rice",
    category: "Cereals",
    variety: "BPT 5204 Samba Mahsuri",
    quantity: 90,
    unit: "quintal",
    quality: "A",
    moisture: 13.0,
    aiQualityScore: 91,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.7,
    demandLevel: "High",
    predictedPrice: 3450,
    priceLogic: {
      baseMSP: 2850,
      gradeMultiplier: 1.10,
      moistureAdjustment: "+₹100 (Optimal)",
      demandBoost: "+₹200 (South India Urban demand)",
    },
    bestPlaceToSell: {
      mandi: "Kurnool APMC Market",
      distanceKm: 20,
      mandiPrice: 3480,
      estimatedFreight: 160,
      netProfitPerQuintal: 3320,
    },
    whenToSell: {
      recommendation: "Hold 1 Week",
      projectedIncrease: "+5%",
      reasoning: "Paddy arrivals moderating in neighboring districts.",
    },
    floorPrice: 2900,
    currentBid: 3350,
    totalBids: 11,
    harvestDate: "2025-01-04",
    location: "Kurnool",
    state: "Andhra Pradesh",
    farmerName: "Ramakrishna Reddy",
    farmerId: "F008",
    imageUrl: "https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(52),
    logisticsMode: "app_arranged",
    weightConfirmed: 90,
    pickupSchedule: { date: "2025-01-07", time: "09:30 AM" },
  },
  {
    id: "9",
    name: "Maize (Yellow Corn)",
    category: "Cereals",
    variety: "DKC 9108 Hybrid",
    quantity: 120,
    unit: "quintal",
    quality: "B",
    moisture: 13.8,
    aiQualityScore: 86,
    aiSuggestedGrade: "B",
    farmerRating: 4.6,
    buyerRating: 4.5,
    demandLevel: "High",
    predictedPrice: 2280,
    priceLogic: {
      baseMSP: 2090,
      gradeMultiplier: 1.04,
      moistureAdjustment: "+₹40 (Acceptable feed moisture)",
      demandBoost: "+₹150 (Poultry feed mill demand)",
    },
    bestPlaceToSell: {
      mandi: "Davanagere APMC",
      distanceKm: 16,
      mandiPrice: 2310,
      estimatedFreight: 110,
      netProfitPerQuintal: 2200,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+1%",
      reasoning: "Feed manufacturing procurement active this week.",
    },
    floorPrice: 2000,
    currentBid: 2240,
    totalBids: 7,
    harvestDate: "2025-01-06",
    location: "Davanagere",
    state: "Karnataka",
    farmerName: "Basavaraj Gowda",
    farmerId: "F009",
    imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(40),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 120,
    pickupSchedule: { date: "2025-01-08", time: "01:00 PM" },
  },
  {
    id: "10",
    name: "Pearl Millet (Bajra)",
    category: "Cereals",
    variety: "HHB 67 Improved",
    quantity: 60,
    unit: "quintal",
    quality: "A",
    moisture: 11.2,
    aiQualityScore: 90,
    aiSuggestedGrade: "A",
    farmerRating: 4.7,
    buyerRating: 4.6,
    demandLevel: "Medium",
    predictedPrice: 2450,
    priceLogic: {
      baseMSP: 2500,
      gradeMultiplier: 1.06,
      moistureAdjustment: "+₹60 (Cleaned & dry)",
      demandBoost: "+₹80 (Winter consumption demand)",
    },
    bestPlaceToSell: {
      mandi: "Jaipur Grain Mandi",
      distanceKm: 22,
      mandiPrice: 2480,
      estimatedFreight: 140,
      netProfitPerQuintal: 2340,
    },
    whenToSell: {
      recommendation: "Hold 1 Week",
      projectedIncrease: "+4%",
      reasoning: "Winter millet bread and livestock feed orders picking up.",
    },
    floorPrice: 2200,
    currentBid: 2410,
    totalBids: 5,
    harvestDate: "2025-01-02",
    location: "Jaipur",
    state: "Rajasthan",
    farmerName: "Mukesh Meena",
    farmerId: "F010",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Grain_millet%2C_early_grain_fill%2C_Tifton%2C_7-3-02.jpg/960px-Grain_millet%2C_early_grain_fill%2C_Tifton%2C_7-3-02.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(60),
    logisticsMode: "app_arranged",
    weightConfirmed: 60,
    pickupSchedule: { date: "2025-01-06", time: "08:30 AM" },
  },
  {
    id: "11",
    name: "Sorghum (Jowar)",
    category: "Cereals",
    variety: "Maldandi M 35-1 (Rabi)",
    quantity: 45,
    unit: "quintal",
    quality: "A",
    moisture: 10.8,
    aiQualityScore: 93,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.8,
    demandLevel: "Surge",
    predictedPrice: 3900,
    priceLogic: {
      baseMSP: 3180,
      gradeMultiplier: 1.15,
      moistureAdjustment: "+₹120 (Pearly white grain)",
      demandBoost: "+₹350 (Maldandi premium)",
    },
    bestPlaceToSell: {
      mandi: "Solapur Agricultural Mandi",
      distanceKm: 15,
      mandiPrice: 3950,
      estimatedFreight: 130,
      netProfitPerQuintal: 3820,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+3%",
      reasoning: "Huge premium for authentic Maldandi grain in Western India.",
    },
    floorPrice: 3400,
    currentBid: 3850,
    totalBids: 13,
    harvestDate: "2025-01-07",
    location: "Solapur",
    state: "Maharashtra",
    farmerName: "Dattatray Shinde",
    farmerId: "F011",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Sorghum_bicolor03.jpg/960px-Sorghum_bicolor03.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(24),
    logisticsMode: "app_arranged",
    weightConfirmed: 45,
    pickupSchedule: { date: "2025-01-08", time: "09:00 AM" },
  },
  {
    id: "12",
    name: "Finger Millet (Ragi)",
    category: "Cereals",
    variety: "GPU 28 Brown Millet",
    quantity: 35,
    unit: "quintal",
    quality: "A",
    moisture: 11.5,
    aiQualityScore: 92,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.9,
    demandLevel: "High",
    predictedPrice: 4150,
    priceLogic: {
      baseMSP: 3846,
      gradeMultiplier: 1.08,
      moistureAdjustment: "+₹80 (Super clean)",
      demandBoost: "+₹220 (Health food processing brands)",
    },
    bestPlaceToSell: {
      mandi: "Mandya APMC Yard",
      distanceKm: 18,
      mandiPrice: 4200,
      estimatedFreight: 150,
      netProfitPerQuintal: 4050,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+2%",
      reasoning: "Packaged superfood brands actively bidding on certified ragi.",
    },
    floorPrice: 3700,
    currentBid: 4100,
    totalBids: 10,
    harvestDate: "2025-01-05",
    location: "Mandya",
    state: "Karnataka",
    farmerName: "Venkatesh Murthy",
    farmerId: "F012",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Ragi_%28Eleusine_coracana%29_BNC.jpg/960px-Ragi_%28Eleusine_coracana%29_BNC.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(32),
    logisticsMode: "app_arranged",
    weightConfirmed: 35,
    pickupSchedule: { date: "2025-01-07", time: "10:00 AM" },
  },

  // ==========================================
  // 2. PULSES (8 Crops)
  // ==========================================
  {
    id: "13",
    name: "Desi Chickpeas (Chana)",
    category: "Pulses",
    variety: "JG 11 Bold Brown",
    quantity: 80,
    unit: "quintal",
    quality: "A",
    moisture: 9.8,
    aiQualityScore: 94,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.8,
    demandLevel: "High",
    predictedPrice: 6250,
    priceLogic: {
      baseMSP: 5440,
      gradeMultiplier: 1.12,
      moistureAdjustment: "+₹120 (Dry & insect-free)",
      demandBoost: "+₹350 (Dal mill procurement)",
    },
    bestPlaceToSell: {
      mandi: "Bikaner Krishi Upaj Mandi",
      distanceKm: 25,
      mandiPrice: 6300,
      estimatedFreight: 200,
      netProfitPerQuintal: 6100,
    },
    whenToSell: {
      recommendation: "Hold 2 Weeks",
      projectedIncrease: "+7%",
      reasoning: "Pre-wedding season pulse consumption boost.",
    },
    floorPrice: 5500,
    currentBid: 6150,
    totalBids: 15,
    harvestDate: "2025-01-04",
    location: "Bikaner",
    state: "Rajasthan",
    farmerName: "Hanuman Ram",
    farmerId: "F013",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Chickpea_BNC.jpg/960px-Chickpea_BNC.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(30),
    logisticsMode: "app_arranged",
    weightConfirmed: 80,
    pickupSchedule: { date: "2025-01-06", time: "11:30 AM" },
  },
  {
    id: "14",
    name: "Kabuli Chana (Dollar Chickpeas)",
    category: "Pulses",
    variety: "Indore Dollar 42-44 Count",
    quantity: 65,
    unit: "quintal",
    quality: "A",
    moisture: 9.2,
    aiQualityScore: 97,
    aiSuggestedGrade: "A",
    farmerRating: 5.0,
    buyerRating: 4.9,
    demandLevel: "Surge",
    predictedPrice: 11800,
    priceLogic: {
      baseMSP: 8500,
      gradeMultiplier: 1.25,
      moistureAdjustment: "+₹300 (Jumbo grain bold)",
      demandBoost: "+₹1200 (Middle East export orders)",
    },
    bestPlaceToSell: {
      mandi: "Indore Chhavani Mandi",
      distanceKm: 12,
      mandiPrice: 11950,
      estimatedFreight: 220,
      netProfitPerQuintal: 11730,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+3%",
      reasoning: "Export containers loading at Nhava Sheva port.",
    },
    floorPrice: 9800,
    currentBid: 11600,
    totalBids: 18,
    harvestDate: "2025-01-08",
    location: "Indore",
    state: "Madhya Pradesh",
    farmerName: "Anand Patidar",
    farmerId: "F014",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Cicer_arietinum_-_Osaka_Museum_of_Natural_History_-_DSC07848.JPG/960px-Cicer_arietinum_-_Osaka_Museum_of_Natural_History_-_DSC07848.JPG",
    status: "live",
    auctionEndsAt: getAuctionEnd(20),
    logisticsMode: "app_arranged",
    weightConfirmed: 65,
    pickupSchedule: { date: "2025-01-09", time: "09:00 AM" },
  },
  {
    id: "15",
    name: "Pigeon Pea (Toor / Arhar Dal)",
    category: "Pulses",
    variety: "Maruti ICP 8863 Red Gram",
    quantity: 50,
    unit: "quintal",
    quality: "A",
    moisture: 10.4,
    aiQualityScore: 93,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.7,
    demandLevel: "High",
    predictedPrice: 10400,
    priceLogic: {
      baseMSP: 7000,
      gradeMultiplier: 1.18,
      moistureAdjustment: "+₹150 (Properly sun-dried)",
      demandBoost: "+₹900 (National buffer stock deficit)",
    },
    bestPlaceToSell: {
      mandi: "Kalaburagi (Gulbarga) Dal Mandi",
      distanceKm: 10,
      mandiPrice: 10550,
      estimatedFreight: 140,
      netProfitPerQuintal: 10410,
    },
    whenToSell: {
      recommendation: "Hold 3 Weeks",
      projectedIncrease: "+8%",
      reasoning: "Government buffer procurement price expected to hike.",
    },
    floorPrice: 8900,
    currentBid: 10250,
    totalBids: 14,
    harvestDate: "2025-01-06",
    location: "Kalaburagi",
    state: "Karnataka",
    farmerName: "Shivanna Patil",
    farmerId: "F015",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Cajanus_cajan_Steve_Hurst_1.jpg/960px-Cajanus_cajan_Steve_Hurst_1.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(42),
    logisticsMode: "app_arranged",
    weightConfirmed: 50,
    pickupSchedule: { date: "2025-01-08", time: "10:30 AM" },
  },
  {
    id: "16",
    name: "Green Gram (Moong Dal)",
    category: "Pulses",
    variety: "IPM 205-7 Virat",
    quantity: 40,
    unit: "quintal",
    quality: "A",
    moisture: 9.9,
    aiQualityScore: 91,
    aiSuggestedGrade: "A",
    farmerRating: 4.7,
    buyerRating: 4.8,
    demandLevel: "Medium",
    predictedPrice: 8350,
    priceLogic: {
      baseMSP: 8558,
      gradeMultiplier: 1.05,
      moistureAdjustment: "+₹100 (Bright green seed coat)",
      demandBoost: "+₹200 (Sprouting quality standard)",
    },
    bestPlaceToSell: {
      mandi: "Akola Krishi Upaj Mandi",
      distanceKm: 14,
      mandiPrice: 8420,
      estimatedFreight: 120,
      netProfitPerQuintal: 8300,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+2%",
      reasoning: "Fresh crop arrivals from southern states starting next week.",
    },
    floorPrice: 7600,
    currentBid: 8200,
    totalBids: 9,
    harvestDate: "2025-01-05",
    location: "Akola",
    state: "Maharashtra",
    farmerName: "Santosh Deshmukh",
    farmerId: "F016",
    imageUrl: "https://images.unsplash.com/photo-1584473457406-6240486418e9?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(38),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 40,
    pickupSchedule: { date: "2025-01-07", time: "02:00 PM" },
  },
  {
    id: "17",
    name: "Black Gram (Urad Dal)",
    category: "Pulses",
    variety: "PU 31 Bold Black",
    quantity: 55,
    unit: "quintal",
    quality: "A",
    moisture: 10.2,
    aiQualityScore: 92,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.7,
    demandLevel: "High",
    predictedPrice: 8750,
    priceLogic: {
      baseMSP: 6950,
      gradeMultiplier: 1.15,
      moistureAdjustment: "+₹110 (Low moisture)",
      demandBoost: "+₹450 (Papad and Idli batter millers)",
    },
    bestPlaceToSell: {
      mandi: "Latur APMC Yard",
      distanceKm: 11,
      mandiPrice: 8820,
      estimatedFreight: 130,
      netProfitPerQuintal: 8690,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+3%",
      reasoning: "Heavy demand from South Indian food processors.",
    },
    floorPrice: 7800,
    currentBid: 8650,
    totalBids: 11,
    harvestDate: "2025-01-07",
    location: "Latur",
    state: "Maharashtra",
    farmerName: "Balasaheb Kadam",
    farmerId: "F017",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Black_gram.jpg/960px-Black_gram.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(50),
    logisticsMode: "app_arranged",
    weightConfirmed: 55,
    pickupSchedule: { date: "2025-01-08", time: "11:00 AM" },
  },
  {
    id: "18",
    name: "Red Lentil (Masoor Dal)",
    category: "Pulses",
    variety: "KLS 218 Small Bold",
    quantity: 45,
    unit: "quintal",
    quality: "A",
    moisture: 10.0,
    aiQualityScore: 90,
    aiSuggestedGrade: "A",
    farmerRating: 4.6,
    buyerRating: 4.6,
    demandLevel: "Medium",
    predictedPrice: 6500,
    priceLogic: {
      baseMSP: 6425,
      gradeMultiplier: 1.05,
      moistureAdjustment: "+₹80 (Cleaned)",
      demandBoost: "+₹150 (Government procurement tender)",
    },
    bestPlaceToSell: {
      mandi: "Sagar Krishi Mandi",
      distanceKm: 19,
      mandiPrice: 6540,
      estimatedFreight: 140,
      netProfitPerQuintal: 6400,
    },
    whenToSell: {
      recommendation: "Hold 1 Week",
      projectedIncrease: "+4%",
      reasoning: "Canadian import tariff discussions may push domestic rates.",
    },
    floorPrice: 5900,
    currentBid: 6420,
    totalBids: 6,
    harvestDate: "2025-01-03",
    location: "Sagar",
    state: "Madhya Pradesh",
    farmerName: "Govind Ahirwar",
    farmerId: "F018",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/3_types_of_lentil.png/960px-3_types_of_lentil.png",
    status: "live",
    auctionEndsAt: getAuctionEnd(44),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 45,
    pickupSchedule: { date: "2025-01-06", time: "03:00 PM" },
  },
  {
    id: "19",
    name: "Kashmiri Rajma (Kidney Beans)",
    category: "Pulses",
    variety: "Bhaderwah Chitra Red-Spotted",
    quantity: 25,
    unit: "quintal",
    quality: "A",
    moisture: 9.0,
    aiQualityScore: 98,
    aiSuggestedGrade: "A",
    farmerRating: 5.0,
    buyerRating: 5.0,
    demandLevel: "Surge",
    predictedPrice: 14800,
    priceLogic: {
      baseMSP: 9500,
      gradeMultiplier: 1.30,
      moistureAdjustment: "+₹300 (Mountain sun-dried)",
      demandBoost: "+₹1800 (Pure organic GI heritage tag)",
    },
    bestPlaceToSell: {
      mandi: "Jammu Grain Terminal",
      distanceKm: 45,
      mandiPrice: 15100,
      estimatedFreight: 450,
      netProfitPerQuintal: 14650,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+2%",
      reasoning: "Luxury hotel chains and organic retailers bidding aggressively.",
    },
    floorPrice: 12500,
    currentBid: 14500,
    totalBids: 21,
    harvestDate: "2025-01-02",
    location: "Bhaderwah",
    state: "Jammu & Kashmir",
    farmerName: "Ghulam Nabi",
    farmerId: "F019",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Red_Rajma_BNC.jpg/960px-Red_Rajma_BNC.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(18),
    logisticsMode: "app_arranged",
    weightConfirmed: 25,
    pickupSchedule: { date: "2025-01-05", time: "09:00 AM" },
  },
  {
    id: "20",
    name: "Cowpea / Black Eyed Pea (Chawli)",
    category: "Pulses",
    variety: "Pusa Sukomal Cream Seed",
    quantity: 30,
    unit: "quintal",
    quality: "B",
    moisture: 10.6,
    aiQualityScore: 88,
    aiSuggestedGrade: "B",
    farmerRating: 4.5,
    buyerRating: 4.6,
    demandLevel: "Medium",
    predictedPrice: 6800,
    priceLogic: {
      baseMSP: 5800,
      gradeMultiplier: 1.06,
      moistureAdjustment: "+₹60 (Standard)",
      demandBoost: "+₹220 (Catering & retail demand)",
    },
    bestPlaceToSell: {
      mandi: "Anand APMC Market",
      distanceKm: 16,
      mandiPrice: 6870,
      estimatedFreight: 130,
      netProfitPerQuintal: 6740,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+1%",
      reasoning: "Steady local consumption pattern.",
    },
    floorPrice: 5900,
    currentBid: 6650,
    totalBids: 7,
    harvestDate: "2025-01-06",
    location: "Anand",
    state: "Gujarat",
    farmerName: "Pravinbhai Patel",
    farmerId: "F020",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Lobia.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(46),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 30,
    pickupSchedule: { date: "2025-01-08", time: "01:30 PM" },
  },

  // ==========================================
  // 3. VEGETABLES (11 Crops)
  // ==========================================
  {
    id: "3",
    name: "Tomatoes",
    category: "Vegetables",
    variety: "Hybrid Shivam (Firm Red)",
    quantity: 20,
    unit: "quintal",
    quality: "A",
    moisture: 88.0,
    aiQualityScore: 89,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.6,
    demandLevel: "Medium",
    predictedPrice: 2150,
    priceLogic: {
      baseMSP: 1700,
      gradeMultiplier: 1.10,
      moistureAdjustment: "+₹0 (Standard fresh)",
      demandBoost: "+₹250 (Retail market deficit)",
    },
    bestPlaceToSell: {
      mandi: "Nashik Wholesale Market",
      distanceKm: 15,
      mandiPrice: 2180,
      estimatedFreight: 200,
      netProfitPerQuintal: 1980,
    },
    whenToSell: {
      recommendation: "Sell Immediately",
      projectedIncrease: "-15%",
      reasoning: "High perishability crop; quality drops within 48 hours.",
    },
    floorPrice: 1800,
    currentBid: 2100,
    totalBids: 15,
    harvestDate: "2025-01-03",
    location: "Nashik",
    state: "Maharashtra",
    farmerName: "Suresh Patil",
    farmerId: "F003",
    imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(16),
    logisticsMode: "app_arranged",
    weightConfirmed: 20,
    pickupSchedule: { date: "2025-01-04", time: "09:00 AM" },
  },
  {
    id: "4",
    name: "Onions",
    category: "Vegetables",
    variety: "Nashik Red (Garwa Summer)",
    quantity: 80,
    unit: "quintal",
    quality: "B",
    moisture: 14.2,
    aiQualityScore: 78,
    aiSuggestedGrade: "B",
    farmerRating: 4.5,
    buyerRating: 4.4,
    demandLevel: "Medium",
    predictedPrice: 1600,
    priceLogic: {
      baseMSP: 1200,
      gradeMultiplier: 1.0,
      moistureAdjustment: "-₹50 (Slightly elevated moisture)",
      demandBoost: "+₹300 (Export quota opened)",
    },
    bestPlaceToSell: {
      mandi: "Lasalgaon Onion Mandi",
      distanceKm: 5,
      mandiPrice: 1620,
      estimatedFreight: 90,
      netProfitPerQuintal: 1530,
    },
    whenToSell: {
      recommendation: "Hold 3 Weeks",
      projectedIncrease: "+18%",
      reasoning: "Cold storage option recommended; onion export policy favorable.",
    },
    floorPrice: 1200,
    currentBid: 1550,
    totalBids: 6,
    harvestDate: "2025-01-02",
    location: "Lasalgaon",
    state: "Maharashtra",
    farmerName: "Mahesh Jadhav",
    farmerId: "F004",
    imageUrl: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(34),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 80,
    pickupSchedule: { date: "2025-01-05", time: "11:00 AM" },
  },
  {
    id: "21",
    name: "Potatoes (Chip Grade)",
    category: "Vegetables",
    variety: "Kufri Chipsona-1 (High Solid)",
    quantity: 150,
    unit: "quintal",
    quality: "A",
    moisture: 79.5,
    aiQualityScore: 95,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.9,
    demandLevel: "Surge",
    predictedPrice: 1950,
    priceLogic: {
      baseMSP: 1400,
      gradeMultiplier: 1.15,
      moistureAdjustment: "+₹100 (Sugar <0.1%, zero browning)",
      demandBoost: "+₹350 (Snack food factory contract)",
    },
    bestPlaceToSell: {
      mandi: "Agra Wholesale Potato Mandi",
      distanceKm: 18,
      mandiPrice: 1980,
      estimatedFreight: 140,
      netProfitPerQuintal: 1840,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+2%",
      reasoning: "Processing plants procuring directly at gate.",
    },
    floorPrice: 1500,
    currentBid: 1920,
    totalBids: 16,
    harvestDate: "2025-01-06",
    location: "Agra",
    state: "Uttar Pradesh",
    farmerName: "Rameshwar Yadav",
    farmerId: "F021",
    imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(26),
    logisticsMode: "app_arranged",
    weightConfirmed: 150,
    pickupSchedule: { date: "2025-01-07", time: "08:00 AM" },
  },
  {
    id: "22",
    name: "Green Chillies",
    category: "Vegetables",
    variety: "G4 Teja Spicy Fresh",
    quantity: 25,
    unit: "quintal",
    quality: "A",
    moisture: 84.0,
    aiQualityScore: 92,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.7,
    demandLevel: "High",
    predictedPrice: 4600,
    priceLogic: {
      baseMSP: 3200,
      gradeMultiplier: 1.12,
      moistureAdjustment: "+₹0 (Fresh crispy pod)",
      demandBoost: "+₹650 (Mumbai wholesale deficit)",
    },
    bestPlaceToSell: {
      mandi: "Kolhapur Shetkari Mandi",
      distanceKm: 12,
      mandiPrice: 4650,
      estimatedFreight: 150,
      netProfitPerQuintal: 4500,
    },
    whenToSell: {
      recommendation: "Sell Immediately",
      projectedIncrease: "-10%",
      reasoning: "Moisture weight loss begins within 24 hours.",
    },
    floorPrice: 3800,
    currentBid: 4520,
    totalBids: 11,
    harvestDate: "2025-01-05",
    location: "Kolhapur",
    state: "Maharashtra",
    farmerName: "Anil Mane",
    farmerId: "F022",
    imageUrl: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(14),
    logisticsMode: "app_arranged",
    weightConfirmed: 25,
    pickupSchedule: { date: "2025-01-06", time: "07:00 AM" },
  },
  {
    id: "23",
    name: "Cauliflower",
    category: "Vegetables",
    variety: "Pusa Snowball K-1 White",
    quantity: 35,
    unit: "quintal",
    quality: "A",
    moisture: 91.0,
    aiQualityScore: 90,
    aiSuggestedGrade: "A",
    farmerRating: 4.7,
    buyerRating: 4.5,
    demandLevel: "Medium",
    predictedPrice: 1850,
    priceLogic: {
      baseMSP: 1300,
      gradeMultiplier: 1.10,
      moistureAdjustment: "+₹0 (Pristine white curds)",
      demandBoost: "+₹220 (Winter wedding catering demand)",
    },
    bestPlaceToSell: {
      mandi: "Malerkotla Sabzi Mandi",
      distanceKm: 10,
      mandiPrice: 1890,
      estimatedFreight: 110,
      netProfitPerQuintal: 1780,
    },
    whenToSell: {
      recommendation: "Sell Immediately",
      projectedIncrease: "-8%",
      reasoning: "Fresh perishable crop; sell within 36 hours.",
    },
    floorPrice: 1400,
    currentBid: 1800,
    totalBids: 8,
    harvestDate: "2025-01-04",
    location: "Malerkotla",
    state: "Punjab",
    farmerName: "Harnek Singh",
    farmerId: "F023",
    imageUrl: "https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(20),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 35,
    pickupSchedule: { date: "2025-01-05", time: "06:30 AM" },
  },
  {
    id: "24",
    name: "Cabbage",
    category: "Vegetables",
    variety: "Golden Acre Solid Head",
    quantity: 40,
    unit: "quintal",
    quality: "B",
    moisture: 92.0,
    aiQualityScore: 86,
    aiSuggestedGrade: "B",
    farmerRating: 4.6,
    buyerRating: 4.5,
    demandLevel: "Stable",
    predictedPrice: 1250,
    priceLogic: {
      baseMSP: 950,
      gradeMultiplier: 1.05,
      moistureAdjustment: "+₹0 (Compact heavy heads)",
      demandBoost: "+₹140 (Canteen & restaurant demand)",
    },
    bestPlaceToSell: {
      mandi: "Pune Market Yard Gultekdi",
      distanceKm: 22,
      mandiPrice: 1280,
      estimatedFreight: 130,
      netProfitPerQuintal: 1150,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+1%",
      reasoning: "Stable demand in Pune metropolitan restaurants.",
    },
    floorPrice: 1000,
    currentBid: 1220,
    totalBids: 5,
    harvestDate: "2025-01-05",
    location: "Pune",
    state: "Maharashtra",
    farmerName: "Tukaram Shinde",
    farmerId: "F024",
    imageUrl: "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(28),
    logisticsMode: "app_arranged",
    weightConfirmed: 40,
    pickupSchedule: { date: "2025-01-06", time: "08:00 AM" },
  },
  {
    id: "25",
    name: "Carrots (Red)",
    category: "Vegetables",
    variety: "Pusa Rudhira Sweet Winter",
    quantity: 50,
    unit: "quintal",
    quality: "A",
    moisture: 88.5,
    aiQualityScore: 93,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.8,
    demandLevel: "High",
    predictedPrice: 2200,
    priceLogic: {
      baseMSP: 1500,
      gradeMultiplier: 1.12,
      moistureAdjustment: "+₹80 (Washed & graded)",
      demandBoost: "+₹300 (Gajar Halwa seasonal demand)",
    },
    bestPlaceToSell: {
      mandi: "Muzaffarnagar Mandi",
      distanceKm: 14,
      mandiPrice: 2240,
      estimatedFreight: 120,
      netProfitPerQuintal: 2120,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+3%",
      reasoning: "Peak sweet carrot winter seasonal consumption.",
    },
    floorPrice: 1700,
    currentBid: 2180,
    totalBids: 12,
    harvestDate: "2025-01-04",
    location: "Muzaffarnagar",
    state: "Uttar Pradesh",
    farmerName: "Choudhary Jaipal",
    farmerId: "F025",
    imageUrl: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(36),
    logisticsMode: "app_arranged",
    weightConfirmed: 50,
    pickupSchedule: { date: "2025-01-06", time: "10:00 AM" },
  },
  {
    id: "26",
    name: "Brinjal / Eggplant",
    category: "Vegetables",
    variety: "Manjari Gota Round Striped",
    quantity: 30,
    unit: "quintal",
    quality: "A",
    moisture: 89.0,
    aiQualityScore: 91,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.7,
    demandLevel: "Medium",
    predictedPrice: 1950,
    priceLogic: {
      baseMSP: 1400,
      gradeMultiplier: 1.08,
      moistureAdjustment: "+₹0 (Glossy tender skin)",
      demandBoost: "+₹240 (Regional Maharashtrian cuisine preference)",
    },
    bestPlaceToSell: {
      mandi: "Ahmednagar APMC Market",
      distanceKm: 11,
      mandiPrice: 1980,
      estimatedFreight: 100,
      netProfitPerQuintal: 1880,
    },
    whenToSell: {
      recommendation: "Sell Immediately",
      projectedIncrease: "-12%",
      reasoning: "Tender skin dulls after 48 hours.",
    },
    floorPrice: 1500,
    currentBid: 1910,
    totalBids: 7,
    harvestDate: "2025-01-05",
    location: "Ahmednagar",
    state: "Maharashtra",
    farmerName: "Pandurang Gite",
    farmerId: "F026",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/960px-Solanum_melongena_24_08_2012_%281%29.JPG",
    status: "live",
    auctionEndsAt: getAuctionEnd(18),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 30,
    pickupSchedule: { date: "2025-01-06", time: "07:30 AM" },
  },
  {
    id: "27",
    name: "Lady Finger (Okra / Bhindi)",
    category: "Vegetables",
    variety: "Radhika Dark Green Hybrid",
    quantity: 22,
    unit: "quintal",
    quality: "A",
    moisture: 87.0,
    aiQualityScore: 94,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.8,
    demandLevel: "High",
    predictedPrice: 3800,
    priceLogic: {
      baseMSP: 2600,
      gradeMultiplier: 1.15,
      moistureAdjustment: "+₹0 (Tender fiber-free tip)",
      demandBoost: "+₹550 (Export to Gulf markets standard)",
    },
    bestPlaceToSell: {
      mandi: "Surat APMC Mandi",
      distanceKm: 14,
      mandiPrice: 3850,
      estimatedFreight: 140,
      netProfitPerQuintal: 3710,
    },
    whenToSell: {
      recommendation: "Sell Immediately",
      projectedIncrease: "-14%",
      reasoning: "Requires cold transport for maximum tenderness.",
    },
    floorPrice: 3000,
    currentBid: 3750,
    totalBids: 13,
    harvestDate: "2025-01-06",
    location: "Surat",
    state: "Gujarat",
    farmerName: "Jayesh Patel",
    farmerId: "F027",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Hong_Kong_Okra_Aug_25_2012.JPG/960px-Hong_Kong_Okra_Aug_25_2012.JPG",
    status: "live",
    auctionEndsAt: getAuctionEnd(12),
    logisticsMode: "app_arranged",
    weightConfirmed: 22,
    pickupSchedule: { date: "2025-01-07", time: "06:00 AM" },
  },
  {
    id: "28",
    name: "Green Capsicum (Bell Pepper)",
    category: "Vegetables",
    variety: "Indra F1 Polyhouse Grown",
    quantity: 28,
    unit: "quintal",
    quality: "A",
    moisture: 91.5,
    aiQualityScore: 96,
    aiSuggestedGrade: "A",
    farmerRating: 5.0,
    buyerRating: 4.9,
    demandLevel: "Surge",
    predictedPrice: 4200,
    priceLogic: {
      baseMSP: 2800,
      gradeMultiplier: 1.20,
      moistureAdjustment: "+₹100 (Thick walled, 4-lobed)",
      demandBoost: "+₹600 (Delhi NCR supermarket buyers)",
    },
    bestPlaceToSell: {
      mandi: "Shimla Fruit & Veg Yard",
      distanceKm: 25,
      mandiPrice: 4280,
      estimatedFreight: 200,
      netProfitPerQuintal: 4080,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+4%",
      reasoning: "Polyhouse capsicum commands premium in urban Delhi retail.",
    },
    floorPrice: 3400,
    currentBid: 4150,
    totalBids: 15,
    harvestDate: "2025-01-07",
    location: "Shimla",
    state: "Himachal Pradesh",
    farmerName: "Rajinder Thakur",
    farmerId: "F028",
    imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(22),
    logisticsMode: "app_arranged",
    weightConfirmed: 28,
    pickupSchedule: { date: "2025-01-08", time: "08:30 AM" },
  },
  {
    id: "29",
    name: "Green Peas (Matar)",
    category: "Vegetables",
    variety: "GS 10 Sweet Green",
    quantity: 45,
    unit: "quintal",
    quality: "A",
    moisture: 78.0,
    aiQualityScore: 95,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.9,
    demandLevel: "High",
    predictedPrice: 3600,
    priceLogic: {
      baseMSP: 2500,
      gradeMultiplier: 1.15,
      moistureAdjustment: "+₹100 (Full 9-10 pod seed count)",
      demandBoost: "+₹450 (Frozen food processing procurement)",
    },
    bestPlaceToSell: {
      mandi: "Jabalpur Krishi Mandi",
      distanceKm: 15,
      mandiPrice: 3650,
      estimatedFreight: 140,
      netProfitPerQuintal: 3510,
    },
    whenToSell: {
      recommendation: "Sell Immediately",
      projectedIncrease: "-10%",
      reasoning: "Peak season supplies driving prices down week-over-week.",
    },
    floorPrice: 2800,
    currentBid: 3550,
    totalBids: 14,
    harvestDate: "2025-01-05",
    location: "Jabalpur",
    state: "Madhya Pradesh",
    farmerName: "Virendra Chouhan",
    farmerId: "F029",
    imageUrl: "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(15),
    logisticsMode: "app_arranged",
    weightConfirmed: 45,
    pickupSchedule: { date: "2025-01-06", time: "09:00 AM" },
  },

  // ==========================================
  // 4. FRUITS (10 Crops)
  // ==========================================
  {
    id: "30",
    name: "Alphonso Mango (Hapus)",
    category: "Fruits",
    variety: "Ratnagiri GI Tagged Pure Hapus",
    quantity: 40,
    unit: "quintal",
    quality: "A",
    moisture: 82.0,
    aiQualityScore: 98,
    aiSuggestedGrade: "A",
    farmerRating: 5.0,
    buyerRating: 5.0,
    demandLevel: "Surge",
    predictedPrice: 18500,
    priceLogic: {
      baseMSP: 12000,
      gradeMultiplier: 1.30,
      moistureAdjustment: "+₹500 (Tree ripened GI certified)",
      demandBoost: "+₹2500 (Export & premium gifting tier)",
    },
    bestPlaceToSell: {
      mandi: "Vashi APMC Fruit Market",
      distanceKm: 320,
      mandiPrice: 19000,
      estimatedFreight: 900,
      netProfitPerQuintal: 18100,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+5%",
      reasoning: "Early season arrivals secure top bid prices from exporters.",
    },
    floorPrice: 15000,
    currentBid: 18200,
    totalBids: 24,
    harvestDate: "2025-01-08",
    location: "Ratnagiri",
    state: "Maharashtra",
    farmerName: "Sachin Sawant",
    farmerId: "F030",
    imageUrl: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(24),
    logisticsMode: "app_arranged",
    weightConfirmed: 40,
    pickupSchedule: { date: "2025-01-09", time: "08:00 AM" },
  },
  {
    id: "31",
    name: "Banana",
    category: "Fruits",
    variety: "Grand Naine (G9 Export Spec)",
    quantity: 120,
    unit: "quintal",
    quality: "A",
    moisture: 75.0,
    aiQualityScore: 94,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.9,
    demandLevel: "High",
    predictedPrice: 2450,
    priceLogic: {
      baseMSP: 1600,
      gradeMultiplier: 1.15,
      moistureAdjustment: "+₹80 (Blemish free 8-9 inch hands)",
      demandBoost: "+₹380 (Middle East reefer export)",
    },
    bestPlaceToSell: {
      mandi: "Jalgaon Banana Mandi",
      distanceKm: 16,
      mandiPrice: 2490,
      estimatedFreight: 120,
      netProfitPerQuintal: 2370,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+2%",
      reasoning: "Cold chain reefers loading for Dubai port.",
    },
    floorPrice: 1900,
    currentBid: 2420,
    totalBids: 15,
    harvestDate: "2025-01-07",
    location: "Jalgaon",
    state: "Maharashtra",
    farmerName: "Nitin Chaudhari",
    farmerId: "F031",
    imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(30),
    logisticsMode: "app_arranged",
    weightConfirmed: 120,
    pickupSchedule: { date: "2025-01-08", time: "07:00 AM" },
  },
  {
    id: "32",
    name: "Apple",
    category: "Fruits",
    variety: "Royal Delicious Kinnaur Grade Extra",
    quantity: 70,
    unit: "quintal",
    quality: "A",
    moisture: 84.5,
    aiQualityScore: 97,
    aiSuggestedGrade: "A",
    farmerRating: 5.0,
    buyerRating: 4.9,
    demandLevel: "Surge",
    predictedPrice: 9200,
    priceLogic: {
      baseMSP: 6500,
      gradeMultiplier: 1.20,
      moistureAdjustment: "+₹200 (CA storage conditioned)",
      demandBoost: "+₹1200 (Tier-1 metro fruit retail)",
    },
    bestPlaceToSell: {
      mandi: "Azadpur Mandi, Delhi",
      distanceKm: 280,
      mandiPrice: 9450,
      estimatedFreight: 650,
      netProfitPerQuintal: 8800,
    },
    whenToSell: {
      recommendation: "Hold 2 Weeks",
      projectedIncrease: "+7%",
      reasoning: "Domestic apple stock depletion creates price premium.",
    },
    floorPrice: 7500,
    currentBid: 9100,
    totalBids: 19,
    harvestDate: "2025-01-03",
    location: "Kinnaur",
    state: "Himachal Pradesh",
    farmerName: "Prem Singh Negi",
    farmerId: "F032",
    imageUrl: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(48),
    logisticsMode: "app_arranged",
    weightConfirmed: 70,
    pickupSchedule: { date: "2025-01-06", time: "11:00 AM" },
  },
  {
    id: "33",
    name: "Nagpur Orange (Mandarin)",
    category: "Fruits",
    variety: "Nagpur Santra Sweet & Juicy",
    quantity: 60,
    unit: "quintal",
    quality: "A",
    moisture: 87.0,
    aiQualityScore: 92,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.7,
    demandLevel: "High",
    predictedPrice: 4800,
    priceLogic: {
      baseMSP: 3200,
      gradeMultiplier: 1.15,
      moistureAdjustment: "+₹150 (High Brix >11 sugar content)",
      demandBoost: "+₹650 (Juice processors & retail fruit markets)",
    },
    bestPlaceToSell: {
      mandi: "Kalamna Market, Nagpur",
      distanceKm: 12,
      mandiPrice: 4880,
      estimatedFreight: 140,
      netProfitPerQuintal: 4740,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+3%",
      reasoning: "High juice yield attracts beverage buyers.",
    },
    floorPrice: 3800,
    currentBid: 4750,
    totalBids: 12,
    harvestDate: "2025-01-06",
    location: "Nagpur",
    state: "Maharashtra",
    farmerName: "Diliprao Raut",
    farmerId: "F033",
    imageUrl: "https://images.unsplash.com/photo-1547514701-42782101795e?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(26),
    logisticsMode: "app_arranged",
    weightConfirmed: 60,
    pickupSchedule: { date: "2025-01-08", time: "10:00 AM" },
  },
  {
    id: "34",
    name: "Grapes (Table & Raisin)",
    category: "Fruits",
    variety: "Thompson Seedless Green",
    quantity: 50,
    unit: "quintal",
    quality: "A",
    moisture: 81.0,
    aiQualityScore: 95,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.9,
    demandLevel: "Surge",
    predictedPrice: 6800,
    priceLogic: {
      baseMSP: 4500,
      gradeMultiplier: 1.20,
      moistureAdjustment: "+₹180 (Berry size 18mm+ export)",
      demandBoost: "+₹900 (European export packaging)",
    },
    bestPlaceToSell: {
      mandi: "Sangli Grape Market",
      distanceKm: 18,
      mandiPrice: 6920,
      estimatedFreight: 180,
      netProfitPerQuintal: 6740,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+2%",
      reasoning: "EU residue-tested batch cleared for export.",
    },
    floorPrice: 5400,
    currentBid: 6700,
    totalBids: 17,
    harvestDate: "2025-01-07",
    location: "Sangli",
    state: "Maharashtra",
    farmerName: "Vasantrao Patil",
    farmerId: "F034",
    imageUrl: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(32),
    logisticsMode: "app_arranged",
    weightConfirmed: 50,
    pickupSchedule: { date: "2025-01-09", time: "07:30 AM" },
  },
  {
    id: "35",
    name: "Pomegranate (Anar)",
    category: "Fruits",
    variety: "Bhagwa Deep Red Arils",
    quantity: 45,
    unit: "quintal",
    quality: "A",
    moisture: 79.0,
    aiQualityScore: 96,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 5.0,
    demandLevel: "Surge",
    predictedPrice: 12500,
    priceLogic: {
      baseMSP: 8000,
      gradeMultiplier: 1.25,
      moistureAdjustment: "+₹350 (Dark ruby arils >350g fruit)",
      demandBoost: "+₹1500 (Domestic & international air freight orders)",
    },
    bestPlaceToSell: {
      mandi: "Solapur Anar Mandi",
      distanceKm: 20,
      mandiPrice: 12750,
      estimatedFreight: 250,
      netProfitPerQuintal: 12500,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+4%",
      reasoning: "Excellent Bhagwa quality getting top export bids.",
    },
    floorPrice: 9500,
    currentBid: 12300,
    totalBids: 22,
    harvestDate: "2025-01-08",
    location: "Solapur",
    state: "Maharashtra",
    farmerName: "Appasaheb Salunkhe",
    farmerId: "F035",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Pomegranate03_edit.jpg/960px-Pomegranate03_edit.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(20),
    logisticsMode: "app_arranged",
    weightConfirmed: 45,
    pickupSchedule: { date: "2025-01-09", time: "09:00 AM" },
  },
  {
    id: "36",
    name: "Guava (Amrood)",
    category: "Fruits",
    variety: "Allahabad Safeda Sweet White",
    quantity: 35,
    unit: "quintal",
    quality: "A",
    moisture: 83.0,
    aiQualityScore: 91,
    aiSuggestedGrade: "A",
    farmerRating: 4.7,
    buyerRating: 4.6,
    demandLevel: "Medium",
    predictedPrice: 2800,
    priceLogic: {
      baseMSP: 1900,
      gradeMultiplier: 1.10,
      moistureAdjustment: "+₹60 (Thin skin, few seeds)",
      demandBoost: "+₹380 (Fresh fruit retail & pulp buyers)",
    },
    bestPlaceToSell: {
      mandi: "Prayagraj Fruit Mandi",
      distanceKm: 14,
      mandiPrice: 2860,
      estimatedFreight: 120,
      netProfitPerQuintal: 2740,
    },
    whenToSell: {
      recommendation: "Sell Immediately",
      projectedIncrease: "-12%",
      reasoning: "Ripens rapidly; optimal shelf life 3 days.",
    },
    floorPrice: 2200,
    currentBid: 2750,
    totalBids: 9,
    harvestDate: "2025-01-06",
    location: "Prayagraj",
    state: "Uttar Pradesh",
    farmerName: "Ramswaroop Maurya",
    farmerId: "F036",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Guava_pink_fruit.jpg/960px-Guava_pink_fruit.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(18),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 35,
    pickupSchedule: { date: "2025-01-07", time: "08:00 AM" },
  },
  {
    id: "37",
    name: "Papaya",
    category: "Fruits",
    variety: "Taiwan 786 Red Lady Semi-Ripened",
    quantity: 60,
    unit: "quintal",
    quality: "A",
    moisture: 88.0,
    aiQualityScore: 93,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.8,
    demandLevel: "High",
    predictedPrice: 2250,
    priceLogic: {
      baseMSP: 1500,
      gradeMultiplier: 1.12,
      moistureAdjustment: "+₹70 (Firm shipping maturity)",
      demandBoost: "+₹320 (High lycopene sweet red pulp)",
    },
    bestPlaceToSell: {
      mandi: "Baramati Krishi Mandi",
      distanceKm: 16,
      mandiPrice: 2290,
      estimatedFreight: 130,
      netProfitPerQuintal: 2160,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+2%",
      reasoning: "Firm green-tinged fruit ideal for interstate transport.",
    },
    floorPrice: 1800,
    currentBid: 2220,
    totalBids: 11,
    harvestDate: "2025-01-05",
    location: "Baramati",
    state: "Maharashtra",
    farmerName: "Sunil Jagtap",
    farmerId: "F037",
    imageUrl: "https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(28),
    logisticsMode: "app_arranged",
    weightConfirmed: 60,
    pickupSchedule: { date: "2025-01-07", time: "09:30 AM" },
  },
  {
    id: "38",
    name: "Watermelon",
    category: "Fruits",
    variety: "Kiran 2 Black Beauty",
    quantity: 100,
    unit: "quintal",
    quality: "A",
    moisture: 93.0,
    aiQualityScore: 90,
    aiSuggestedGrade: "A",
    farmerRating: 4.7,
    buyerRating: 4.6,
    demandLevel: "High",
    predictedPrice: 1450,
    priceLogic: {
      baseMSP: 950,
      gradeMultiplier: 1.10,
      moistureAdjustment: "+₹40 (Uniform 3-4kg melons)",
      demandBoost: "+₹220 (Metropolitan city juice centers)",
    },
    bestPlaceToSell: {
      mandi: "Anantapur Fruit Market",
      distanceKm: 22,
      mandiPrice: 1490,
      estimatedFreight: 150,
      netProfitPerQuintal: 1340,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+3%",
      reasoning: "Warm weather early demand in southern urban centers.",
    },
    floorPrice: 1100,
    currentBid: 1420,
    totalBids: 8,
    harvestDate: "2025-01-04",
    location: "Anantapur",
    state: "Andhra Pradesh",
    farmerName: "B. Ramanjaneyulu",
    farmerId: "F038",
    imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(36),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 100,
    pickupSchedule: { date: "2025-01-06", time: "07:00 AM" },
  },
  {
    id: "39",
    name: "Pineapple",
    category: "Fruits",
    variety: "Queen Sweet Aromatic",
    quantity: 50,
    unit: "quintal",
    quality: "A",
    moisture: 86.0,
    aiQualityScore: 94,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.8,
    demandLevel: "Medium",
    predictedPrice: 3200,
    priceLogic: {
      baseMSP: 2100,
      gradeMultiplier: 1.12,
      moistureAdjustment: "+₹90 (Golden yellow ripe eye)",
      demandBoost: "+₹450 (Processing and fresh fruit chains)",
    },
    bestPlaceToSell: {
      mandi: "Siliguri Fruit Terminal",
      distanceKm: 28,
      mandiPrice: 3280,
      estimatedFreight: 220,
      netProfitPerQuintal: 3060,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+2%",
      reasoning: "High aroma fruit batch ready for direct retail delivery.",
    },
    floorPrice: 2500,
    currentBid: 3150,
    totalBids: 10,
    harvestDate: "2025-01-06",
    location: "Siliguri",
    state: "West Bengal",
    farmerName: "Bikash Barman",
    farmerId: "F039",
    imageUrl: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(40),
    logisticsMode: "app_arranged",
    weightConfirmed: 50,
    pickupSchedule: { date: "2025-01-08", time: "11:30 AM" },
  },

  // ==========================================
  // 5. OILSEEDS (6 Crops)
  // ==========================================
  {
    id: "40",
    name: "Mustard Seed (Sarson)",
    category: "Oilseeds",
    variety: "Pusa Bold High Oil (42%)",
    quantity: 85,
    unit: "quintal",
    quality: "A",
    moisture: 7.2,
    aiQualityScore: 95,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.9,
    demandLevel: "Surge",
    predictedPrice: 6450,
    priceLogic: {
      baseMSP: 5650,
      gradeMultiplier: 1.10,
      moistureAdjustment: "+₹180 (Oil content >41.5% premium)",
      demandBoost: "+₹380 (Kachi Ghani expeller mills)",
    },
    bestPlaceToSell: {
      mandi: "Bharatpur Mustard Mandi",
      distanceKm: 14,
      mandiPrice: 6510,
      estimatedFreight: 140,
      netProfitPerQuintal: 6370,
    },
    whenToSell: {
      recommendation: "Hold 2 Weeks",
      projectedIncrease: "+6%",
      reasoning: "Oil mill crushers accumulating inventory before peak season.",
    },
    floorPrice: 5600,
    currentBid: 6350,
    totalBids: 16,
    harvestDate: "2025-01-07",
    location: "Bharatpur",
    state: "Rajasthan",
    farmerName: "Radheshyam Sharma",
    farmerId: "F040",
    imageUrl: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(44),
    logisticsMode: "app_arranged",
    weightConfirmed: 85,
    pickupSchedule: { date: "2025-01-09", time: "10:00 AM" },
  },
  {
    id: "41",
    name: "Soybean",
    category: "Oilseeds",
    variety: "JS 335 Yellow Seed",
    quantity: 110,
    unit: "quintal",
    quality: "A",
    moisture: 9.8,
    aiQualityScore: 93,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.7,
    demandLevel: "High",
    predictedPrice: 5150,
    priceLogic: {
      baseMSP: 4892,
      gradeMultiplier: 1.08,
      moistureAdjustment: "+₹120 (Optimal storage moisture <10%)",
      demandBoost: "+₹220 (Soymeal de-oiled cake export)",
    },
    bestPlaceToSell: {
      mandi: "Ujjain Krishi Upaj Mandi",
      distanceKm: 18,
      mandiPrice: 5200,
      estimatedFreight: 150,
      netProfitPerQuintal: 5050,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+2%",
      reasoning: "Current crushing margins are attractive for regional solvent plants.",
    },
    floorPrice: 4700,
    currentBid: 5080,
    totalBids: 12,
    harvestDate: "2025-01-05",
    location: "Ujjain",
    state: "Madhya Pradesh",
    farmerName: "Mangilal Patidar",
    farmerId: "F041",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/82/Soybean.USDA.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(36),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 110,
    pickupSchedule: { date: "2025-01-07", time: "01:00 PM" },
  },
  {
    id: "42",
    name: "Groundnut / Peanut (Moongphali)",
    category: "Oilseeds",
    variety: "Kadiri 6 Bold Kernel (50% Oil)",
    quantity: 70,
    unit: "quintal",
    quality: "A",
    moisture: 7.5,
    aiQualityScore: 96,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.9,
    demandLevel: "High",
    predictedPrice: 7200,
    priceLogic: {
      baseMSP: 6377,
      gradeMultiplier: 1.12,
      moistureAdjustment: "+₹180 (Aflatoxin-free certified)",
      demandBoost: "+₹450 (HPS export and peanut butter brands)",
    },
    bestPlaceToSell: {
      mandi: "Junagadh APMC Yard",
      distanceKm: 15,
      mandiPrice: 7280,
      estimatedFreight: 160,
      netProfitPerQuintal: 7120,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+3%",
      reasoning: "Peanut butter and confectionery export demand peak.",
    },
    floorPrice: 6200,
    currentBid: 7100,
    totalBids: 15,
    harvestDate: "2025-01-06",
    location: "Junagadh",
    state: "Gujarat",
    farmerName: "Bhaveshbhai Vaghani",
    farmerId: "F042",
    imageUrl: "https://images.unsplash.com/photo-1567894340315-735d7c361db0?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(28),
    logisticsMode: "app_arranged",
    weightConfirmed: 70,
    pickupSchedule: { date: "2025-01-08", time: "09:00 AM" },
  },
  {
    id: "43",
    name: "Sunflower Seeds",
    category: "Oilseeds",
    variety: "KBSH 44 High Oleic Hybrid",
    quantity: 40,
    unit: "quintal",
    quality: "A",
    moisture: 8.0,
    aiQualityScore: 91,
    aiSuggestedGrade: "A",
    farmerRating: 4.7,
    buyerRating: 4.7,
    demandLevel: "Medium",
    predictedPrice: 6100,
    priceLogic: {
      baseMSP: 6760,
      gradeMultiplier: 1.05,
      moistureAdjustment: "+₹100 (Black plump seed)",
      demandBoost: "+₹220 (Refined cooking oil refineries)",
    },
    bestPlaceToSell: {
      mandi: "Bellary APMC Mandi",
      distanceKm: 20,
      mandiPrice: 6160,
      estimatedFreight: 150,
      netProfitPerQuintal: 6010,
    },
    whenToSell: {
      recommendation: "Hold 1 Week",
      projectedIncrease: "+4%",
      reasoning: "Import duty on refined sunflower oil being revised.",
    },
    floorPrice: 5500,
    currentBid: 6020,
    totalBids: 8,
    harvestDate: "2025-01-04",
    location: "Bellary",
    state: "Karnataka",
    farmerName: "Mallikarjun Reddy",
    farmerId: "F043",
    imageUrl: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(42),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 40,
    pickupSchedule: { date: "2025-01-07", time: "11:00 AM" },
  },
  {
    id: "44",
    name: "Sesame Seeds (Til)",
    category: "Oilseeds",
    variety: "RT 351 White Hulled Grade",
    quantity: 30,
    unit: "quintal",
    quality: "A",
    moisture: 6.5,
    aiQualityScore: 97,
    aiSuggestedGrade: "A",
    farmerRating: 5.0,
    buyerRating: 4.9,
    demandLevel: "Surge",
    predictedPrice: 15200,
    priceLogic: {
      baseMSP: 8635,
      gradeMultiplier: 1.35,
      moistureAdjustment: "+₹400 (Pure white 99.9% purity)",
      demandBoost: "+₹2200 (Makar Sankranti & bakery export demand)",
    },
    bestPlaceToSell: {
      mandi: "Sumerpur Grain & Oilseed Mandi",
      distanceKm: 24,
      mandiPrice: 15450,
      estimatedFreight: 200,
      netProfitPerQuintal: 15250,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+3%",
      reasoning: "Festival consumption surge and Asian bakery export contracts.",
    },
    floorPrice: 13000,
    currentBid: 14950,
    totalBids: 19,
    harvestDate: "2025-01-07",
    location: "Sumerpur",
    state: "Rajasthan",
    farmerName: "Kishanlal Choudhary",
    farmerId: "F044",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Black_sesame.jpg/960px-Black_sesame.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(22),
    logisticsMode: "app_arranged",
    weightConfirmed: 30,
    pickupSchedule: { date: "2025-01-09", time: "08:30 AM" },
  },
  {
    id: "45",
    name: "Castor Seed",
    category: "Oilseeds",
    variety: "GCH 7 High Ricinoleic Hybrid",
    quantity: 65,
    unit: "quintal",
    quality: "A",
    moisture: 7.0,
    aiQualityScore: 92,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.8,
    demandLevel: "Medium",
    predictedPrice: 6200,
    priceLogic: {
      baseMSP: 5400,
      gradeMultiplier: 1.10,
      moistureAdjustment: "+₹120 (48% oil content)",
      demandBoost: "+₹350 (Industrial lubricants export)",
    },
    bestPlaceToSell: {
      mandi: "Mehsana APMC Market",
      distanceKm: 16,
      mandiPrice: 6270,
      estimatedFreight: 140,
      netProfitPerQuintal: 6130,
    },
    whenToSell: {
      recommendation: "Hold 2 Weeks",
      projectedIncrease: "+5%",
      reasoning: "Global chemical manufacturers placing quarterly replenishment orders.",
    },
    floorPrice: 5300,
    currentBid: 6120,
    totalBids: 10,
    harvestDate: "2025-01-05",
    location: "Mehsana",
    state: "Gujarat",
    farmerName: "Jagdishbhai Prajapati",
    farmerId: "F045",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Ricinus_communis_008.JPG/960px-Ricinus_communis_008.JPG",
    status: "live",
    auctionEndsAt: getAuctionEnd(48),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 65,
    pickupSchedule: { date: "2025-01-08", time: "10:00 AM" },
  },

  // ==========================================
  // 6. CASH CROPS (5 Crops)
  // ==========================================
  {
    id: "5",
    name: "Cotton",
    category: "Cash Crops",
    variety: "Bt Cotton (Long Staple >29mm)",
    quantity: 30,
    unit: "quintal",
    quality: "A",
    moisture: 7.5,
    aiQualityScore: 95,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.9,
    demandLevel: "High",
    predictedPrice: 7400,
    priceLogic: {
      baseMSP: 6620,
      gradeMultiplier: 1.15,
      moistureAdjustment: "+₹200 (Low moisture premium)",
      demandBoost: "+₹400 (Textile factory demand)",
    },
    bestPlaceToSell: {
      mandi: "Guntur Cotton Market",
      distanceKm: 18,
      mandiPrice: 7450,
      estimatedFreight: 250,
      netProfitPerQuintal: 7200,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+1%",
      reasoning: "Textile buyers bidding actively at peak rates.",
    },
    floorPrice: 6500,
    currentBid: 7200,
    totalBids: 9,
    harvestDate: "2024-12-28",
    location: "Guntur",
    state: "Andhra Pradesh",
    farmerName: "Venkata Rao",
    farmerId: "F005",
    imageUrl: "https://images.unsplash.com/photo-1594897030264-ab7d87efc473?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(38),
    logisticsMode: "app_arranged",
    weightConfirmed: 30,
    pickupSchedule: { date: "2025-01-06", time: "08:00 AM" },
  },
  {
    id: "6",
    name: "Sugarcane",
    category: "Cash Crops",
    variety: "Co 0238 High Recovery",
    quantity: 200,
    unit: "quintal",
    quality: "A",
    moisture: 72.0,
    aiQualityScore: 90,
    aiSuggestedGrade: "A",
    farmerRating: 4.6,
    buyerRating: 4.7,
    demandLevel: "Low",
    predictedPrice: 430,
    priceLogic: {
      baseMSP: 350,
      gradeMultiplier: 1.05,
      moistureAdjustment: "+₹0 (High sucrose)",
      demandBoost: "+₹40 (Sugar Mill crush season)",
    },
    bestPlaceToSell: {
      mandi: "Meerut Sugar Mill Gate",
      distanceKm: 10,
      mandiPrice: 435,
      estimatedFreight: 30,
      netProfitPerQuintal: 405,
    },
    whenToSell: {
      recommendation: "Deliver to Mill Direct",
      projectedIncrease: "0%",
      reasoning: "Crushing season agreement active.",
    },
    floorPrice: 350,
    currentBid: 420,
    totalBids: 4,
    harvestDate: "2025-01-08",
    location: "Meerut",
    state: "Uttar Pradesh",
    farmerName: "Amit Sharma",
    farmerId: "F006",
    imageUrl: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(24),
    logisticsMode: "app_arranged",
    weightConfirmed: 200,
    pickupSchedule: { date: "2025-01-07", time: "07:00 AM" },
  },
  {
    id: "46",
    name: "Raw Jute",
    category: "Cash Crops",
    variety: "TD-58 Golden Fibre",
    quantity: 50,
    unit: "quintal",
    quality: "A",
    moisture: 14.0,
    aiQualityScore: 92,
    aiSuggestedGrade: "A",
    farmerRating: 4.7,
    buyerRating: 4.8,
    demandLevel: "High",
    predictedPrice: 5350,
    priceLogic: {
      baseMSP: 5050,
      gradeMultiplier: 1.08,
      moistureAdjustment: "+₹100 (Well-retted golden sheen)",
      demandBoost: "+₹220 (Packaging sacks mandate by Government)",
    },
    bestPlaceToSell: {
      mandi: "Murshidabad Jute Yard",
      distanceKm: 18,
      mandiPrice: 5410,
      estimatedFreight: 150,
      netProfitPerQuintal: 5260,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+2%",
      reasoning: "Jute packaging mills operating at full capacity.",
    },
    floorPrice: 4700,
    currentBid: 5280,
    totalBids: 8,
    harvestDate: "2025-01-04",
    location: "Murshidabad",
    state: "West Bengal",
    farmerName: "Subhash Mondal",
    farmerId: "F046",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Jute_-_Kolkata_2003-10-31_00538.JPG/960px-Jute_-_Kolkata_2003-10-31_00538.JPG",
    status: "live",
    auctionEndsAt: getAuctionEnd(46),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 50,
    pickupSchedule: { date: "2025-01-07", time: "11:00 AM" },
  },
  {
    id: "47",
    name: "Tobacco (Flue-Cured Virginia)",
    category: "Cash Crops",
    variety: "FCV Grade-1 Bright Lemon",
    quantity: 35,
    unit: "quintal",
    quality: "A",
    moisture: 12.0,
    aiQualityScore: 96,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 5.0,
    demandLevel: "Surge",
    predictedPrice: 24500,
    priceLogic: {
      baseMSP: 17500,
      gradeMultiplier: 1.25,
      moistureAdjustment: "+₹400 (Uniform cured color)",
      demandBoost: "+₹2500 (Tobacco Board export quota auctions)",
    },
    bestPlaceToSell: {
      mandi: "Tobacco Board Auction Platform, Ongole",
      distanceKm: 25,
      mandiPrice: 24900,
      estimatedFreight: 350,
      netProfitPerQuintal: 24550,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+3%",
      reasoning: "International leaf merchant auctions bidding at seasonal high.",
    },
    floorPrice: 20000,
    currentBid: 24200,
    totalBids: 18,
    harvestDate: "2025-01-06",
    location: "Ongole",
    state: "Andhra Pradesh",
    farmerName: "K. Subba Rao",
    farmerId: "F047",
    imageUrl: "https://images.unsplash.com/photo-1544476915-ed1370594142?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(26),
    logisticsMode: "app_arranged",
    weightConfirmed: 35,
    pickupSchedule: { date: "2025-01-08", time: "09:30 AM" },
  },
  {
    id: "48",
    name: "Natural Rubber (Sheet)",
    category: "Cash Crops",
    variety: "ISNR 20 Ribbed Smoked Sheet (RSS-4)",
    quantity: 40,
    unit: "quintal",
    quality: "A",
    moisture: 0.8,
    aiQualityScore: 95,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.8,
    demandLevel: "High",
    predictedPrice: 19800,
    priceLogic: {
      baseMSP: 16000,
      gradeMultiplier: 1.15,
      moistureAdjustment: "+₹200 (Clean smoke curing, no mould)",
      demandBoost: "+₹1400 (Automotive tyre manufacturing demand)",
    },
    bestPlaceToSell: {
      mandi: "Kottayam Rubber Market",
      distanceKm: 12,
      mandiPrice: 20100,
      estimatedFreight: 220,
      netProfitPerQuintal: 19880,
    },
    whenToSell: {
      recommendation: "Hold 1 Week",
      projectedIncrease: "+5%",
      reasoning: "Global natural rubber prices climbing in Tokyo & Singapore exchanges.",
    },
    floorPrice: 17500,
    currentBid: 19600,
    totalBids: 14,
    harvestDate: "2025-01-05",
    location: "Kottayam",
    state: "Kerala",
    farmerName: "Mathew Thomas",
    farmerId: "F048",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Caoutchouc_naturel.jpg/960px-Caoutchouc_naturel.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(34),
    logisticsMode: "app_arranged",
    weightConfirmed: 40,
    pickupSchedule: { date: "2025-01-07", time: "10:30 AM" },
  },

  // ==========================================
  // 7. SPICES & PLANTATION (9 Crops)
  // ==========================================
  {
    id: "49",
    name: "Turmeric (Haldi)",
    category: "Spices",
    variety: "Salem / Rajapuri Curcumin >4.5%",
    quantity: 35,
    unit: "quintal",
    quality: "A",
    moisture: 9.5,
    aiQualityScore: 97,
    aiSuggestedGrade: "A",
    farmerRating: 5.0,
    buyerRating: 4.9,
    demandLevel: "Surge",
    predictedPrice: 16800,
    priceLogic: {
      baseMSP: 11000,
      gradeMultiplier: 1.30,
      moistureAdjustment: "+₹400 (High finger polish)",
      demandBoost: "+₹2100 (Pharma curcumin extractors)",
    },
    bestPlaceToSell: {
      mandi: "Sangli Haldi Mandi",
      distanceKm: 15,
      mandiPrice: 17100,
      estimatedFreight: 240,
      netProfitPerQuintal: 16860,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+3%",
      reasoning: "Pharmaceutical extractors competing for certified 4.5% curcumin lots.",
    },
    floorPrice: 14000,
    currentBid: 16600,
    totalBids: 20,
    harvestDate: "2025-01-08",
    location: "Sangli",
    state: "Maharashtra",
    farmerName: "Dadaso Mohite",
    farmerId: "F049",
    imageUrl: "https://images.unsplash.com/photo-1768729341334-666d6fe1385a?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(20),
    logisticsMode: "app_arranged",
    weightConfirmed: 35,
    pickupSchedule: { date: "2025-01-09", time: "09:00 AM" },
  },
  {
    id: "50",
    name: "Ginger (Fresh Adrak)",
    category: "Spices",
    variety: "Rio de Janeiro Plump Rhizome",
    quantity: 40,
    unit: "quintal",
    quality: "A",
    moisture: 82.0,
    aiQualityScore: 93,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.8,
    demandLevel: "High",
    predictedPrice: 8500,
    priceLogic: {
      baseMSP: 6000,
      gradeMultiplier: 1.15,
      moistureAdjustment: "+₹150 (Clean soil-free bold fingers)",
      demandBoost: "+₹850 (Winter culinary & herbal tea demand)",
    },
    bestPlaceToSell: {
      mandi: "Wayanad Spices Mandi",
      distanceKm: 20,
      mandiPrice: 8620,
      estimatedFreight: 180,
      netProfitPerQuintal: 8440,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+2%",
      reasoning: "Strong winter seasonal demand in northern consumer hubs.",
    },
    floorPrice: 7200,
    currentBid: 8350,
    totalBids: 13,
    harvestDate: "2025-01-06",
    location: "Wayanad",
    state: "Kerala",
    farmerName: "Jose Joseph",
    farmerId: "F050",
    imageUrl: "https://images.unsplash.com/photo-1774125364904-de15e430e8f6?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(28),
    logisticsMode: "app_arranged",
    weightConfirmed: 40,
    pickupSchedule: { date: "2025-01-08", time: "10:00 AM" },
  },
  {
    id: "51",
    name: "Garlic (Lehsun)",
    category: "Spices",
    variety: "Yamuna Safed G-50 Bold White",
    quantity: 50,
    unit: "quintal",
    quality: "A",
    moisture: 11.5,
    aiQualityScore: 95,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.9,
    demandLevel: "Surge",
    predictedPrice: 13500,
    priceLogic: {
      baseMSP: 8000,
      gradeMultiplier: 1.25,
      moistureAdjustment: "+₹300 (Cured 40mm+ cloves)",
      demandBoost: "+₹2200 (National market supply tightness)",
    },
    bestPlaceToSell: {
      mandi: "Mandsaur Garlic Mandi",
      distanceKm: 12,
      mandiPrice: 13800,
      estimatedFreight: 200,
      netProfitPerQuintal: 13600,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+4%",
      reasoning: "Highest garlic price index of the fiscal quarter.",
    },
    floorPrice: 11000,
    currentBid: 13200,
    totalBids: 22,
    harvestDate: "2025-01-07",
    location: "Mandsaur",
    state: "Madhya Pradesh",
    farmerName: "Bhaironlal Dangi",
    farmerId: "F051",
    imageUrl: "https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(16),
    logisticsMode: "app_arranged",
    weightConfirmed: 50,
    pickupSchedule: { date: "2025-01-08", time: "11:00 AM" },
  },
  {
    id: "52",
    name: "Dry Red Chilli",
    category: "Spices",
    variety: "Teja Guntur S17 Deep Red Hot",
    quantity: 45,
    unit: "quintal",
    quality: "A",
    moisture: 9.0,
    aiQualityScore: 96,
    aiSuggestedGrade: "A",
    farmerRating: 5.0,
    buyerRating: 4.9,
    demandLevel: "Surge",
    predictedPrice: 21500,
    priceLogic: {
      baseMSP: 15000,
      gradeMultiplier: 1.25,
      moistureAdjustment: "+₹500 (SHU 75,000+ pungency)",
      demandBoost: "+₹2800 (China, Vietnam, and Sri Lanka oleoresin export)",
    },
    bestPlaceToSell: {
      mandi: "Guntur Mirchi Yard",
      distanceKm: 8,
      mandiPrice: 21900,
      estimatedFreight: 180,
      netProfitPerQuintal: 21720,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+3%",
      reasoning: "Record high export inquiry for Teja S17 variety.",
    },
    floorPrice: 18500,
    currentBid: 21200,
    totalBids: 26,
    harvestDate: "2025-01-08",
    location: "Guntur",
    state: "Andhra Pradesh",
    farmerName: "Chalasani Prasad",
    farmerId: "F052",
    imageUrl: "https://images.unsplash.com/photo-1766158554170-1e8b1899c8ae?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(18),
    logisticsMode: "app_arranged",
    weightConfirmed: 45,
    pickupSchedule: { date: "2025-01-09", time: "08:00 AM" },
  },
  {
    id: "53",
    name: "Black Pepper (Kali Mirch)",
    category: "Spices",
    variety: "Panniyur 1 Bold Black Garbled",
    quantity: 20,
    unit: "quintal",
    quality: "A",
    moisture: 10.5,
    aiQualityScore: 97,
    aiSuggestedGrade: "A",
    farmerRating: 5.0,
    buyerRating: 5.0,
    demandLevel: "High",
    predictedPrice: 65000,
    priceLogic: {
      baseMSP: 48000,
      gradeMultiplier: 1.20,
      moistureAdjustment: "+₹1200 (Bulk density >550 g/L)",
      demandBoost: "+₹7500 (Spice Board Malabar export grade)",
    },
    bestPlaceToSell: {
      mandi: "Kochi Spice Market",
      distanceKm: 65,
      mandiPrice: 65800,
      estimatedFreight: 550,
      netProfitPerQuintal: 65250,
    },
    whenToSell: {
      recommendation: "Hold 3 Weeks",
      projectedIncrease: "+6%",
      reasoning: "Global pepper shortage in Vietnam pushing Indian Malabar rates.",
    },
    floorPrice: 56000,
    currentBid: 64200,
    totalBids: 18,
    harvestDate: "2025-01-04",
    location: "Idukki",
    state: "Kerala",
    farmerName: "Antony Kurian",
    farmerId: "F053",
    imageUrl: "https://images.unsplash.com/photo-1777483997189-9d934b0f177d?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(44),
    logisticsMode: "app_arranged",
    weightConfirmed: 20,
    pickupSchedule: { date: "2025-01-07", time: "11:00 AM" },
  },
  {
    id: "54",
    name: "Green Cardamom (Elaichi)",
    category: "Spices",
    variety: "Alleppey Extra Bold 8mm+",
    quantity: 10,
    unit: "quintal",
    quality: "A",
    moisture: 9.8,
    aiQualityScore: 99,
    aiSuggestedGrade: "A",
    farmerRating: 5.0,
    buyerRating: 5.0,
    demandLevel: "Surge",
    predictedPrice: 245000,
    priceLogic: {
      baseMSP: 175000,
      gradeMultiplier: 1.30,
      moistureAdjustment: "+₹6000 (8mm+ pristine green capsule)",
      demandBoost: "+₹28000 (Middle East royal gifting & gourmet confectionery)",
    },
    bestPlaceToSell: {
      mandi: "Spices Board E-Auction, Bodinayakanur",
      distanceKm: 35,
      mandiPrice: 248000,
      estimatedFreight: 800,
      netProfitPerQuintal: 247200,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+4%",
      reasoning: "Electronic auction buyers competing for supreme green 8mm lots.",
    },
    floorPrice: 210000,
    currentBid: 243000,
    totalBids: 31,
    harvestDate: "2025-01-08",
    location: "Bodinayakanur",
    state: "Tamil Nadu",
    farmerName: "Murugan Selvam",
    farmerId: "F054",
    imageUrl: "https://images.unsplash.com/photo-1642255486695-a52c59347cfa?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(20),
    logisticsMode: "app_arranged",
    weightConfirmed: 10,
    pickupSchedule: { date: "2025-01-09", time: "10:30 AM" },
  },
  {
    id: "55",
    name: "Cumin Seeds (Jeera)",
    category: "Spices",
    variety: "GC 4 Machine Cleaned Bold (99.5% Purity)",
    quantity: 40,
    unit: "quintal",
    quality: "A",
    moisture: 7.8,
    aiQualityScore: 98,
    aiSuggestedGrade: "A",
    farmerRating: 5.0,
    buyerRating: 4.9,
    demandLevel: "Surge",
    predictedPrice: 32500,
    priceLogic: {
      baseMSP: 22000,
      gradeMultiplier: 1.25,
      moistureAdjustment: "+₹800 (Machine sortex cleaned)",
      demandBoost: "+₹4500 (Global export dominance from Unjha)",
    },
    bestPlaceToSell: {
      mandi: "Unjha APMC Mandi",
      distanceKm: 14,
      mandiPrice: 32900,
      estimatedFreight: 300,
      netProfitPerQuintal: 32600,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+3%",
      reasoning: "World's largest cumin market seeing strong global orders.",
    },
    floorPrice: 27500,
    currentBid: 32100,
    totalBids: 24,
    harvestDate: "2025-01-07",
    location: "Unjha",
    state: "Gujarat",
    farmerName: "Kanti Patel",
    farmerId: "F055",
    imageUrl: "https://images.unsplash.com/photo-1600791102844-208e695205f6?w=600&auto=format&fit=crop&q=80",
    status: "live",
    auctionEndsAt: getAuctionEnd(24),
    logisticsMode: "app_arranged",
    weightConfirmed: 40,
    pickupSchedule: { date: "2025-01-09", time: "09:00 AM" },
  },
  {
    id: "56",
    name: "Coriander Seeds (Dhaniya)",
    category: "Spices",
    variety: "Kumbhraj Badami Round Aromatic",
    quantity: 50,
    unit: "quintal",
    quality: "A",
    moisture: 8.5,
    aiQualityScore: 92,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.7,
    demandLevel: "High",
    predictedPrice: 8400,
    priceLogic: {
      baseMSP: 6500,
      gradeMultiplier: 1.15,
      moistureAdjustment: "+₹150 (High essential oil content)",
      demandBoost: "+₹800 (Spices powder manufacturers)",
    },
    bestPlaceToSell: {
      mandi: "Kota Bhamashah Mandi",
      distanceKm: 18,
      mandiPrice: 8480,
      estimatedFreight: 140,
      netProfitPerQuintal: 8340,
    },
    whenToSell: {
      recommendation: "Hold 2 Weeks",
      projectedIncrease: "+5%",
      reasoning: "Masala brands replenishing stock before summer wedding rush.",
    },
    floorPrice: 7200,
    currentBid: 8250,
    totalBids: 11,
    harvestDate: "2025-01-05",
    location: "Kota",
    state: "Rajasthan",
    farmerName: "Ramgopal Meena",
    farmerId: "F056",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Coriander_Seeds.jpg/960px-Coriander_Seeds.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(38),
    logisticsMode: "buyer_pickup",
    weightConfirmed: 50,
    pickupSchedule: { date: "2025-01-08", time: "11:00 AM" },
  },
  {
    id: "57",
    name: "Fennel Seeds (Saunf)",
    category: "Spices",
    variety: "Gujarat Fennel 11 Extra Green",
    quantity: 35,
    unit: "quintal",
    quality: "A",
    moisture: 8.0,
    aiQualityScore: 94,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.8,
    demandLevel: "High",
    predictedPrice: 18500,
    priceLogic: {
      baseMSP: 13000,
      gradeMultiplier: 1.20,
      moistureAdjustment: "+₹350 (Natural deep green color)",
      demandBoost: "+₹1800 (Mukhwas & export beverage flavoring)",
    },
    bestPlaceToSell: {
      mandi: "Abu Road Spices Mandi",
      distanceKm: 22,
      mandiPrice: 18750,
      estimatedFreight: 200,
      netProfitPerQuintal: 18550,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+3%",
      reasoning: "Excellent premium green grade fetching high bids.",
    },
    floorPrice: 15500,
    currentBid: 18200,
    totalBids: 14,
    harvestDate: "2025-01-06",
    location: "Abu Road",
    state: "Rajasthan",
    farmerName: "Nathuram Gurjar",
    farmerId: "F057",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Foeniculum_vulgare_seeds.jpg/960px-Foeniculum_vulgare_seeds.jpg",
    status: "live",
    auctionEndsAt: getAuctionEnd(30),
    logisticsMode: "app_arranged",
    weightConfirmed: 35,
    pickupSchedule: { date: "2025-01-08", time: "10:30 AM" },
  },
];
