





export const mockCrops = [
  {
    id: "1",
    name: "Basmati Rice",
    variety: "Pusa 1121",
    quantity: 50,
    unit: "quintal",
    quality: "A",
    moisture: 12.5,
    aiQualityScore: 94,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.8,
    demandLevel: "High",
    predictedPrice: 4350,
    priceLogic: {
      baseMSP: 3800,
      gradeMultiplier: 1.12,
      moistureAdjustment: "+₹150 (Optimal <13%)",
      demandBoost: "+₹250 (Export surge)",
    },
    bestPlaceToSell: {
      mandi: "Karnal Grain Market",
      distanceKm: 12,
      mandiPrice: 4380,
      estimatedFreight: 180,
      netProfitPerQuintal: 4200,
    },
    whenToSell: {
      recommendation: "Hold 2 Weeks",
      projectedIncrease: "+12%",
      reasoning: "Festival demand spike expected around harvest completion.",
    },
    floorPrice: 3500,
    currentBid: 4200,
    totalBids: 12,
    harvestDate: "2025-01-10",
    location: "Karnal",
    state: "Haryana",
    farmerName: "Rajesh Kumar",
    farmerId: "F001",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400",
    status: "live",
    auctionEndsAt: "2025-01-05T18:00:00Z",
    logisticsMode: "app_arranged", // "buyer_pickup" or "app_arranged"
    weightConfirmed: 50,
    pickupSchedule: { date: "2025-01-06", time: "10:00 AM" },
  },
  {
    id: "2",
    name: "Wheat",
    variety: "HD 3086",
    quantity: 100,
    unit: "quintal",
    quality: "A",
    moisture: 11.8,
    aiQualityScore: 92,
    aiSuggestedGrade: "A",
    farmerRating: 4.7,
    buyerRating: 4.9,
    demandLevel: "High",
    predictedPrice: 2700,
    priceLogic: {
      baseMSP: 2275,
      gradeMultiplier: 1.08,
      moistureAdjustment: "+₹120 (Dry & clean)",
      demandBoost: "+₹180 (Flour mill demand)",
    },
    bestPlaceToSell: {
      mandi: "Ludhiana Central Mandi",
      distanceKm: 8,
      mandiPrice: 2720,
      estimatedFreight: 120,
      netProfitPerQuintal: 2600,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+2%",
      reasoning: "Current prices are peak; major supply arrivals next week.",
    },
    floorPrice: 2200,
    currentBid: 2650,
    totalBids: 8,
    harvestDate: "2025-01-05",
    location: "Ludhiana",
    state: "Punjab",
    farmerName: "Gurpreet Singh",
    farmerId: "F002",
    imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400",
    status: "live",
    auctionEndsAt: "2025-01-04T15:00:00Z",
    logisticsMode: "buyer_pickup",
    weightConfirmed: 100,
    pickupSchedule: { date: "2025-01-05", time: "02:00 PM" },
  },
  {
    id: "3",
    name: "Tomatoes",
    variety: "Hybrid",
    quantity: 20,
    unit: "quintal",
    quality: "A",
    moisture: 88.0,
    aiQualityScore: 89,
    aiSuggestedGrade: "A",
    farmerRating: 4.8,
    buyerRating: 4.6,
    demandLevel: "Medium",
    predictedPrice: 2150,
    priceLogic: {
      baseMSP: 1700,
      gradeMultiplier: 1.10,
      moistureAdjustment: "+₹0 (Standard fresh)",
      demandBoost: "+₹250 (Retail market deficit)",
    },
    bestPlaceToSell: {
      mandi: "Nashik Wholesale Market",
      distanceKm: 15,
      mandiPrice: 2180,
      estimatedFreight: 200,
      netProfitPerQuintal: 1980,
    },
    whenToSell: {
      recommendation: "Sell Immediately",
      projectedIncrease: "-15%",
      reasoning: "High perishability crop; quality drops within 48 hours.",
    },
    floorPrice: 1800,
    currentBid: 2100,
    totalBids: 15,
    harvestDate: "2025-01-03",
    location: "Nashik",
    state: "Maharashtra",
    farmerName: "Suresh Patil",
    farmerId: "F003",
    imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400",
    status: "live",
    auctionEndsAt: "2025-01-03T20:00:00Z",
    logisticsMode: "app_arranged",
    weightConfirmed: 20,
    pickupSchedule: { date: "2025-01-04", time: "09:00 AM" },
  },
  {
    id: "4",
    name: "Onions",
    variety: "Nashik Red",
    quantity: 80,
    unit: "quintal",
    quality: "B",
    moisture: 14.2,
    aiQualityScore: 78,
    aiSuggestedGrade: "B",
    farmerRating: 4.5,
    buyerRating: 4.4,
    demandLevel: "Medium",
    predictedPrice: 1600,
    priceLogic: {
      baseMSP: 1200,
      gradeMultiplier: 1.0,
      moistureAdjustment: "-₹50 (Slightly elevated moisture)",
      demandBoost: "+₹300 (Export quota opened)",
    },
    bestPlaceToSell: {
      mandi: "Lasalgaon Onion Mandi",
      distanceKm: 5,
      mandiPrice: 1620,
      estimatedFreight: 90,
      netProfitPerQuintal: 1530,
    },
    whenToSell: {
      recommendation: "Hold 3 Weeks",
      projectedIncrease: "+18%",
      reasoning: "Cold storage option recommended; onion export policy favorable.",
    },
    floorPrice: 1200,
    currentBid: 1550,
    totalBids: 6,
    harvestDate: "2025-01-02",
    location: "Lasalgaon",
    state: "Maharashtra",
    farmerName: "Mahesh Jadhav",
    farmerId: "F004",
    imageUrl: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400",
    status: "live",
    auctionEndsAt: "2025-01-04T12:00:00Z",
    logisticsMode: "buyer_pickup",
    weightConfirmed: 80,
    pickupSchedule: { date: "2025-01-05", time: "11:00 AM" },
  },
  {
    id: "5",
    name: "Cotton",
    variety: "Bt Cotton",
    quantity: 30,
    unit: "quintal",
    quality: "A",
    moisture: 7.5,
    aiQualityScore: 95,
    aiSuggestedGrade: "A",
    farmerRating: 4.9,
    buyerRating: 4.9,
    demandLevel: "High",
    predictedPrice: 7400,
    priceLogic: {
      baseMSP: 6620,
      gradeMultiplier: 1.15,
      moistureAdjustment: "+₹200 (Low moisture premium)",
      demandBoost: "+₹400 (Textile factory demand)",
    },
    bestPlaceToSell: {
      mandi: "Guntur Cotton Market",
      distanceKm: 18,
      mandiPrice: 7450,
      estimatedFreight: 250,
      netProfitPerQuintal: 7200,
    },
    whenToSell: {
      recommendation: "Sell Now",
      projectedIncrease: "+1%",
      reasoning: "Textile buyers bidding actively at peak rates.",
    },
    floorPrice: 6500,
    currentBid: 7200,
    totalBids: 9,
    harvestDate: "2024-12-28",
    location: "Guntur",
    state: "Andhra Pradesh",
    farmerName: "Venkata Rao",
    farmerId: "F005",
    imageUrl: "https://images.unsplash.com/photo-1594897030264-ab7d87efc473?w=400",
    status: "live",
    auctionEndsAt: "2025-01-05T10:00:00Z",
    logisticsMode: "app_arranged",
    weightConfirmed: 30,
    pickupSchedule: { date: "2025-01-06", time: "08:00 AM" },
  },
  {
    id: "6",
    name: "Sugarcane",
    variety: "Co 0238",
    quantity: 200,
    unit: "quintal",
    quality: "A",
    moisture: 72.0,
    aiQualityScore: 90,
    aiSuggestedGrade: "A",
    farmerRating: 4.6,
    buyerRating: 4.7,
    demandLevel: "Low",
    predictedPrice: 430,
    priceLogic: {
      baseMSP: 350,
      gradeMultiplier: 1.05,
      moistureAdjustment: "+₹0 (High sucrose)",
      demandBoost: "+₹40 (Sugar Mill crush season)",
    },
    bestPlaceToSell: {
      mandi: "Meerut Sugar Mill Gate",
      distanceKm: 10,
      mandiPrice: 435,
      estimatedFreight: 30,
      netProfitPerQuintal: 405,
    },
    whenToSell: {
      recommendation: "Deliver to Mill Direct",
      projectedIncrease: "0%",
      reasoning: "Crushing season agreement active.",
    },
    floorPrice: 350,
    currentBid: 420,
    totalBids: 4,
    harvestDate: "2025-01-08",
    location: "Meerut",
    state: "Uttar Pradesh",
    farmerName: "Amit Sharma",
    farmerId: "F006",
    imageUrl: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400",
    status: "live",
    auctionEndsAt: "2025-01-06T16:00:00Z",
    logisticsMode: "app_arranged",
    weightConfirmed: 200,
    pickupSchedule: { date: "2025-01-07", time: "07:00 AM" },
  },
];

export const mockBids = [
  { id: "B1", cropId: "1", buyerId: "BU001", buyerName: "Agromart Exports", amount: 4200, timestamp: "2025-01-03T10:30:00Z", status: "active" },
  { id: "B2", cropId: "1", buyerId: "BU002", buyerName: "Fresh Foods Ltd", amount: 4100, timestamp: "2025-01-03T10:15:00Z", status: "outbid" },
  { id: "B3", cropId: "1", buyerId: "BU003", buyerName: "Rice India Co", amount: 4000, timestamp: "2025-01-03T09:45:00Z", status: "outbid" },
  { id: "B4", cropId: "2", buyerId: "BU001", buyerName: "Agromart Exports", amount: 2650, timestamp: "2025-01-03T11:00:00Z", status: "active" },
  { id: "B5", cropId: "2", buyerId: "BU004", buyerName: "Grain Traders", amount: 2500, timestamp: "2025-01-03T10:00:00Z", status: "outbid" },
];

export const mockFarmerStats = {
  totalListings: 12,
  activeBids: 47,
  completedSales: 8,
  totalEarnings: 485000,
  avgPriceIncrease: 18.5,
};

export const mockFactoryContracts = [
  {
    id: "FC-101",
    factoryName: "PepsiCo India (Lays Division)",
    cropTarget: "Potato (FL-2027 Variety)",
    location: "Jalandhar, Punjab",
    guaranteedPrice: 1850,
    unit: "quintal",
    targetQuantity: 5000,
    committedQuantity: 3450,
    minFarmerCommitment: 50,
    harvestWindow: "Feb 15 - Mar 10, 2025",
    advancePaymentPercent: 20,
    requiredMoisture: "< 14%",
    requiredGrade: "Grade A Chip-Quality",
    joinedFarmers: 28,
    description: "Exclusive contract for chip-grade potato cultivation with free seed distribution & expert agronomist guidance.",
    status: "active",
  },
  {
    id: "FC-102",
    factoryName: "Haldiram Snacks Pvt Ltd",
    cropTarget: "Chickpeas / Desi Chana",
    location: "Nagpur, Maharashtra",
    guaranteedPrice: 5800,
    unit: "quintal",
    targetQuantity: 2000,
    committedQuantity: 1400,
    minFarmerCommitment: 30,
    harvestWindow: "Mar 01 - Mar 30, 2025",
    advancePaymentPercent: 25,
    requiredMoisture: "< 10%",
    requiredGrade: "Grade A Bold",
    joinedFarmers: 16,
    description: "Bulk procurement for snacks manufacturing with quality bonus of ₹200/q for moisture under 9%.",
    status: "active",
  },
  {
    id: "FC-103",
    factoryName: "Vardhman Textiles Ltd",
    cropTarget: "Bt Cotton (Staple > 29mm)",
    location: "Bhavnagar, Gujarat",
    guaranteedPrice: 7600,
    unit: "quintal",
    targetQuantity: 3000,
    committedQuantity: 2800,
    minFarmerCommitment: 40,
    harvestWindow: "Jan 20 - Feb 28, 2025",
    advancePaymentPercent: 15,
    requiredMoisture: "< 8%",
    requiredGrade: "Grade A Premium Fiber",
    joinedFarmers: 22,
    description: "Long-staple cotton contract farming pool with instant weighbridge payout upon delivery.",
    status: "active",
  },
];

export const cropCategories = [
  "All Crops",
  "Cereals",
  "Pulses",
  "Vegetables",
  "Fruits",
  "Oilseeds",
  "Cash Crops",
  "Spices",
];

export const qualityGrades = [
  { value: "A", label: "Grade A - Premium" },
  { value: "B", label: "Grade B - Standard" },
  { value: "C", label: "Grade C - Economy" },
];

export const indianStates = [
  "All States",
  "Andhra Pradesh",
  "Bihar",
  "Gujarat",
  "Haryana",
  "Karnataka",
  "Madhya Pradesh",
  "Maharashtra",
  "Punjab",
  "Rajasthan",
  "Tamil Nadu",
  "Telangana",
  "Uttar Pradesh",
  "West Bengal",
];
